name: Cache Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f5dc905

      - name: prime-cache-f5dc905
        run: |
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit"
          else
            echo "Cache miss"
          fi
